package com.tkdhhh.api.entity;


import java.io.Serializable;

public class Question implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.questionId
     *
     * @mbg.generated Sun Jan 20 00:50:41 CST 2019
     */
    private Integer questionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.image
     *
     * @mbg.generated Sun Jan 20 00:50:41 CST 2019
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.questionOne
     *
     * @mbg.generated Sun Jan 20 00:50:41 CST 2019
     */
    private String questionone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.questionTwo
     *
     * @mbg.generated Sun Jan 20 00:50:41 CST 2019
     */
    private String questiontwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answerOne
     *
     * @mbg.generated Sun Jan 20 00:50:41 CST 2019
     */
    private String answerone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answerTwo
     *
     * @mbg.generated Sun Jan 20 00:50:41 CST 2019
     */
    private String answertwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answerThree
     *
     * @mbg.generated Sun Jan 20 00:50:41 CST 2019
     */
    private String answerthree;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.questionId
     *
     * @return the value of question.questionId
     *
     * @mbg.generated Sun Jan 20 00:50:41 CST 2019
     */
    public Integer getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.questionId
     *
     * @param questionid the value for question.questionId
     *
     * @mbg.generated Sun Jan 20 00:50:41 CST 2019
     */
    public void setQuestionid(Integer questionid) {
        this.questionid = questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.image
     *
     * @return the value of question.image
     *
     * @mbg.generated Sun Jan 20 00:50:41 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.image
     *
     * @param image the value for question.image
     *
     * @mbg.generated Sun Jan 20 00:50:41 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.questionOne
     *
     * @return the value of question.questionOne
     *
     * @mbg.generated Sun Jan 20 00:50:41 CST 2019
     */
    public String getQuestionone() {
        return questionone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.questionOne
     *
     * @param questionone the value for question.questionOne
     *
     * @mbg.generated Sun Jan 20 00:50:41 CST 2019
     */
    public void setQuestionone(String questionone) {
        this.questionone = questionone == null ? null : questionone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.questionTwo
     *
     * @return the value of question.questionTwo
     *
     * @mbg.generated Sun Jan 20 00:50:41 CST 2019
     */
    public String getQuestiontwo() {
        return questiontwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.questionTwo
     *
     * @param questiontwo the value for question.questionTwo
     *
     * @mbg.generated Sun Jan 20 00:50:41 CST 2019
     */
    public void setQuestiontwo(String questiontwo) {
        this.questiontwo = questiontwo == null ? null : questiontwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answerOne
     *
     * @return the value of question.answerOne
     *
     * @mbg.generated Sun Jan 20 00:50:41 CST 2019
     */
    public String getAnswerone() {
        return answerone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answerOne
     *
     * @param answerone the value for question.answerOne
     *
     * @mbg.generated Sun Jan 20 00:50:41 CST 2019
     */
    public void setAnswerone(String answerone) {
        this.answerone = answerone == null ? null : answerone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answerTwo
     *
     * @return the value of question.answerTwo
     *
     * @mbg.generated Sun Jan 20 00:50:41 CST 2019
     */
    public String getAnswertwo() {
        return answertwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answerTwo
     *
     * @param answertwo the value for question.answerTwo
     *
     * @mbg.generated Sun Jan 20 00:50:41 CST 2019
     */
    public void setAnswertwo(String answertwo) {
        this.answertwo = answertwo == null ? null : answertwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answerThree
     *
     * @return the value of question.answerThree
     *
     * @mbg.generated Sun Jan 20 00:50:41 CST 2019
     */
    public String getAnswerthree() {
        return answerthree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answerThree
     *
     * @param answerthree the value for question.answerThree
     *
     * @mbg.generated Sun Jan 20 00:50:41 CST 2019
     */
    public void setAnswerthree(String answerthree) {
        this.answerthree = answerthree == null ? null : answerthree.trim();
    }
}